apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emeraldflow-db-pvc
  labels:
    app: emeraldflow-db
spec:
  storageClassName: {{ .Values.db.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storageSize | quote }}
