apiVersion: v1
kind: Secret
metadata:
  name: emeraldflow-secret
  labels:
    app: emeraldflow
type: Opaque
data:
  db-pass: {{ .Values.secrets.dbPassword | b64enc | quote }}
  rmq-pass: {{ .Values.secrets.rmqPassword | b64enc | quote }}
