app:
  image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/emeraldflow-app
  tag: "49b5e263626f092b93ffca046e7df0129da681ab"
  replicas: 1
  containerPort: 8080
  servicePort: 8080
db:
  image: emeraldflow-db
  tag: "49b5e263626f092b93ffca046e7df0129da681ab"
  replicas: 1
  containerPort: 3306
  servicePort: 3306
  storageClass: gp2
  storageSize: 3Gi
memcached:
  image: memcached
  tag: "49b5e263626f092b93ffca046e7df0129da681ab"
  replicas: 1
  containerPort: 11211
  servicePort: 11211
rabbitmq:
  image: rabbitmq
  tag: "49b5e263626f092b93ffca046e7df0129da681ab"
  replicas: 1
  containerPort: 5672
  servicePort: 5672
  defaultUser: guest
initcontainers:
  image: busybox
  tag: "49b5e263626f092b93ffca046e7df0129da681ab"
ingress:
  enabled: true
  host: emeraldflow.yourdomain.com
  servicePort: 8080
  certificateArn: "arn:aws:acm:us-east-1:123456789012:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
secrets:
  dbPassword: changeme
  rmqPassword: changeme
dockerregistry:
  enabled: false
  server: https://index.docker.io/v1/
  username: ""
  password: ""
  email: ""

