apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emeraldflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: emeraldflow
  source:
    repoURL: git@github.com:Raphonkzy/emeraldflow-helm.git
    targetRevision: main
    path: helm/emeraldflow
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: emeraldflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true